---
- name: Install DNF packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages.dnf }}"
    state: present

- name: Remove DNF packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages.dnf_deleted }}"
    state: absent
  when: packages.dnf_deleted

- name: Install FlatPak packages
  community.general.flatpak:
    name: "{{ packages.flatpak }}"
    state: present

- name: Remove FlatPak packages
  community.general.flatpak:
    name: "{{ packages.flatpak_deleted }}"
    state: absent
  when: packages.flatpak_deleted

- name: Install pipx
  become: true
  ansible.builtin.dnf:
    name: pipx
    state: present

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.pipx | default([]) }}"

- name: Remove pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages.pipx_deleted | default([]) }}"
