---
- name: Install asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ home }}/.asdf"
    version: "{{ asdf.version | default('master') }}"

- name: Ensure {{ home }}/.bashrc.d dir exists
  ansible.builtin.file:
    path: "{{ home }}/.bashrc.d"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: asdf.rc
  ansible.builtin.copy:
    src: files/asdf.rc
    dest: "{{ home }}/.bashrc.d/asdf.rc"
    mode: u=rw,g=r,o=r

- name: Update asdf
  ansible.builtin.shell: source {{ home }}/.asdf/asdf.sh && asdf update

- name: Install asdf plugins
  ansible.builtin.shell: source {{ home }}/.asdf/asdf.sh && asdf plugin add {{ item.name }}
  register: stdout
  changed_when: "'already added' not in stdout.stdout"
  loop: "{{ asdf.plugins }}"

- name: Update asdf plugins
  # running --all instead of looping on each plugin. It's faster
  ansible.builtin.shell: source {{ home }}/.asdf/asdf.sh && asdf plugin update --all

- name: Install asdf package versions
  ansible.builtin.shell: source {{ home }}/.asdf/asdf.sh && asdf install {{ item.name }} {{ item.version }}
  register: stdout
  when: item.version is defined
  changed_when: "'already installed' not in stdout.stdout"
  loop: "{{ asdf.plugins }}"

- name: Configure asdf defaults
  ansible.builtin.template:
    src: files/tool-versions.j2
    dest: "{{ home }}/.tool-versions"
