---
- name: Ensure {{ home }}/.bashrc.d dir exists
  ansible.builtin.file:
    path: "{{ home }}/.bashrc.d"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: ocl.rc
  ansible.builtin.copy:
    src: files/ocl.rc
    dest: "{{ home }}/.bashrc.d/ocl.rc"
    mode: u=rw,g=r,o=r

- name: app-sre.rc
  ansible.builtin.copy:
    src: files/app-sre.rc
    dest: "{{ home }}/.bashrc.d/app-sre.rc"
    mode: u=rw,g=r,o=r
