---
- name: Ensure {{ home }}/.bashrc.d dir exists
  ansible.builtin.file:
    path: "{{ home }}/.bashrc.d"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy bashrc.d files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: "{{ home }}/.bashrc.d/{{ item }}"
    mode: u=rw,g=r,o=r
  loop:
  - patrick.rc
  - ocl.rc
  - app-sre.rc
  - ps1
  - complete
