---
packages:
  dnf:
  - terminator
  - vim-enhanced
  - tmux
  - sshuttle
  - system-config-printer
  # - fzf
  - just # make alternative, used in https://gitlab.cee.redhat.com/jchevret/aws-acct-mgmt
  - ipcalc
  - openssl
  - htop
  - the_silver_searcher
  - python3-jinja2-cli

  - slack
  - meld
  - gstreamer1-plugin-openh264
  - inkscape

  - podman
  - podman-docker
  - podman-compose
  - buildah
  - skopeo

  # needed for asdf install python
  - gcc
  - zlib-devel
  - bzip2-devel
  - ncurses-devel
  - libffi-devel
  - readline-devel
  - openssl-devel

  - autoconf  

  # needed for rh-pre-commit hook install
  - tk-devel
  - libsqlite3x-devel

  # qontract-reconcile dependencies
  - python3-devel
  - libpq-devel
  - git-secrets
  # - helm --> moving to asdf

  # pipx rh-aws-saml-login
  - krb5-devel

  # - epson-inkjet-printer-escpr2
  dnf_deleted:
  # opensc seems to be causing Firefox to request a cert password constantly
  # Smart card library and applications
  # Found this info in https://source.redhat.com/personal_blogs/setting_up_vpnldapkerberos_sso_on_a_fresh_fedora_33_install
  - opensc
  - golang-github-prometheus
  - golang-github-prometheus-alertmanager

  flatpak:
  - com.bitwarden.desktop
  flatpak_deleted: []

  pipx:
      - rh-aws-saml-login

asdf:
  # version: "v0.13.1"
  plugins:
  - name: oc
    version: 4.14.12
  - name: kubectl
    version: 1.28.3
  - name: helm
    version: 3.11.1
  - name: kubectx
    version: 0.9.5
  - name: terraform
    version: 0.13.7
    # version: 1.6.2
  - name: vault
    version: 1.15.1
  - name: promtool
    version: 2.54.1
  - name: terragrunt
    version: 0.53.1
  - name: python
    version: 3.11.5
  # - name: pipx
  #   version: 1.4.3
  - name: yq
    version: 4.35.2
  - name: awscli
    version: 2.13.31
  - name: golang
    version: 1.21.3
  - name: stern
    version: 1.26.0
  - name: tekton-cli
    version: 0.32.2
  - name: nodejs
    version: 21.1.0
  - name: ruby
    # version: 3.2.2
  - name: kind
    version: 0.20.0
  - name: minikube
    version: 1.32.0
  - name: yarn
    # version: 1.22.19
  - name: uv
    version: 0.5.2 

binaries:
  direct:
  - name: ocm
    url: https://github.com/openshift-online/ocm-cli/releases/latest/download/ocm-linux-amd64
    checksum: https://github.com/openshift-online/ocm-cli/releases/latest/download/ocm-linux-amd64.sha256

  - name: rosa
    url: https://github.com/openshift/rosa/releases/latest/download/rosa-linux-amd64
    checksum: https://github.com/openshift/rosa/releases/latest/download/rosa-linux-amd64.sha256

  targz:
  - name: ocm-backplane
    url: https://github.com/openshift/backplane-cli/releases/download/v0.1.21/ocm-backplane_0.1.21_Linux_x86_64.tar.gz
    include:
    - ocm-backplane

  # - name: promtool
  #   url: https://github.com/prometheus/prometheus/releases/download/v2.33.3/prometheus-2.33.3.linux-amd64.tar.gz
  #   extra_opts: [--strip-components=1]
  #   include:
  #   - promtool

  # - name: amtool
  #   url: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
  #   extra_opts: [--strip-components=1]
  #   include:
  #   - amtool

vscode:
  extensions:
  - eamodio.gitlens
  - Fr43nk.seito-openfile
  # - VisualStudioExptTeam.vscodeintellicode
  # - GitHub.copilot
  - timonwong.shellcheck
  - golang.Go
  - ms-python.python
  - ms-python.vscode-pylance
  - charliermarsh.ruff
  - matangover.mypy
  - bierner.markdown-mermaid
  - samuelcolvin.jinjahtml
  - ms-vscode.makefile-tools
  extensions_deleted: []
  # - ms-python.pylint
  # - ms-python.black-formatter
  # - ms-python.isort
